# Generated by Django 3.1.6 on 2021-02-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Дата создания')),
                ('slug', models.SlugField(auto_created=True, max_length=500, unique=True, verbose_name='ЧПУ')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название статьи')),
                ('preview', models.CharField(max_length=500, verbose_name='Превью')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Флаг активности')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статья',
            },
        ),
    ]
